# Generated by Django 5.0.4 on 2024-04-22 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    
]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('type', models.IntegerField(choices=[(0, 'Offre'), (1, 'Demande')])),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localisation', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('contactInfo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeStg', models.IntegerField(choices=[(1, 'Ouvrier'), (2, 'Technicien'), (3, 'PFE')])),
                ('societe', models.CharField(max_length=200)),
                ('duree', models.IntegerField()),
                ('sujet', models.CharField(max_length=200)),
                ('contactInfo', models.CharField(max_length=200)),
                ('specialite', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student.post')),
                ('intitule', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=200)),
                ('lieu', models.CharField(default='', max_length=200)),
                ('contactInfo', models.CharField(default='', max_length=200)),
            ],
            bases=('student.post',),
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student.post')),
                ('text', models.CharField(max_length=200)),
            ],
            bases=('student.post',),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student.post')),
                ('depart', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=200)),
                ('heuredep', models.TimeField()),
                ('nbresieges', models.IntegerField()),
                ('contactInfo', models.CharField(max_length=200)),
            ],
            bases=('student.post',),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('like', models.BooleanField()),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.post')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.user')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.user'),
        ),
        migrations.CreateModel(
            name='EvenClub',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student.event')),
                ('club', models.CharField(max_length=200)),
            ],
            bases=('student.event',),
        ),
        migrations.CreateModel(
            name='EvenSocial',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student.event')),
                ('prix', models.DecimalField(decimal_places=3, max_digits=15)),
            ],
            bases=('student.event',),
        ),
    ]
