# Generated by Django 5.0.4 on 2024-04-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='slug',
            field=models.SlugField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
