# Generated by Django 5.0.4 on 2024-04-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='duree',
            field=models.DurationField(),
        ),
    ]
