# Generated by Django 5.0.4 on 2024-05-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_stage_duree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='duree',
            field=models.TextField(),
        ),
    ]
